### ISSUE TITLE
After npm run start in /backend getting 404 error

### ISSUE THREAD

**Issue by coursewarefactory** [kannifarhad/CronusFileManager#2]
{"status":"fail","error":{"statusCode":404,"messagetext":"Can't find / on this server!","status":"fail","isOperational":true},"message":"Can't find / on this server!","stack":"Error: Can't find / on this server!\n    at

**Comment by SURONG0808** [comment]
Perhaps, you forget that npm run start

**Comment by linhnguyen9988** [comment]
> {"status":"fail","error":{"statusCode":404,"messagetext":"Can't find / on this server!","status":"fail","isOperational":true},"message":"Can't find / on this server!","stack":"Error: Can't find / on this server!\n at

you must run "npm install" in frontend as well
